const phishnetAssistantKnowledge = [
  'Project knowledge for PhishNet AI:',
  '',
  'Project name:',
  '- PhishNet AI',
  '',
  'Project name meaning:',
  '- PhishNet AI comes from the words "Phishing" and "Internet/Network."',
  '- It also sounds like "fishnet," which inspired the logo: a shield combined with fishnet symbolism to represent protection against phishing threats.',
  '',
  'Short system description:',
  '- PhishNet AI is a web-based phishing detection and awareness system designed to help users identify suspicious URLs, understand phishing indicators, and strengthen phishing awareness through educational content, interactive quizzes, and AI-assisted guidance.',
  '',
  'Study title:',
  '- Development of a Web-Based AI-Driven Phishing Detection and Awareness System for BSIS 2nd Year Students of La Concepcion College',
  '',
  'Researchers:',
  '- Belas, Rem',
  '- Costa, Marco',
  '- Deocampo, John Michael',
  '- Dorado, Leo Lustre',
  '- Hernandez, Luis Christian',
  '- Joaquin, Reymond P.',
  '- Malibago, Hans',
  '- Parati, Justin Kurt',
  '- Ponce, Jiro',
  '- Toel, Michael',
  '',
  'Development note:',
  '- Reymond P. Joaquin served as the primary programmer and lead system developer of PhishNet AI, while the other members contributed as researchers and group members of the study.',
  '',
  'School and adviser:',
  '- School: La Concepcion College, City of San Jose Del Monte, Bulacan',
  '- Course: Bachelor of Science in Information Systems (BSIS)',
  '- Year level: 2nd year students',
  '- Adviser: Elviristo Reyes',
  '',
  'Main features:',
  '- URL phishing detection and analysis',
  '- AI assistant for phishing-related guidance and system support',
  '- Phishing awareness quiz system',
  '- Guest and signed-in quiz access',
  '- Saved quiz progress for signed-in users',
  '- Quiz history with attempt review',
  '- Leaderboard for quiz performance',
  '- User profile with rank, stats, profile note, and unlocked badges',
  '- Badge and milestone system',
  '- Sequential quiz progression and advanced quiz unlocking',
  '- Educational tutorial and phishing awareness guide content',
  '- Forgot password, reset password, and remember me authentication features',
  '',
  'Detailed features:',
  '- Users can analyze suspicious URLs through the phishing detection feature.',
  '- The system provides phishing awareness support through educational content and guided explanations.',
  '- The AI assistant can answer questions about the website, its purpose, features, and phishing-related guidance.',
  '- Guests can access the same quiz environment as signed-in users and answer available quiz sets without signing in.',
  '- Signed-in users can save quiz attempts and keep their awareness progress.',
  '- Signed-in users can view full quiz history with saved scores and attempt records.',
  '- Quiz history allows users to review previous attempts, including correct answers, wrong answers, and explanations.',
  '- The leaderboard shows top users based on saved quiz performance.',
  '- Users can open public quiz profiles from the leaderboard.',
  '- Public quiz profiles show safe and shareable quiz-related stats, earned badges, rank progress, and profile description only.',
  '- The profile page shows account-based rank progress, quiz stats, a short profile note, and unlocked badges.',
  '- The system includes badge and milestone recognition for quiz activity and awareness progress.',
  '- Quiz progression is structured, meaning some advanced quiz sets unlock only after completing earlier quiz paths.',
  '- Signed-in users can unlock more advanced quiz sets based on progress.',
  '- Authentication includes login, signup, logout, remember me, forgot password, and reset password.',
  '- Login redirects can return the user to the page where they started, such as the quiz page or assistant page.',
  '- The quiz page now uses one shared app-style environment for both guest and signed-in users, with locked sections shown to guests when needed.',
  '- Guest users can browse quiz sets and leaderboard content, but history, badges, profile features, saved progress, and advanced tracking are for signed-in users.',
  '- The system includes tutorial and guide sections to help users understand phishing indicators and URL ratings.',
  '',
  'Pages:',
  '- Main page: system overview, scanner, tutorial, and phishing awareness guide',
  '- Quiz page: quiz library, history, leaderboard, profile, and active quiz workspace',
  '- AI Assistant page: interactive assistant for user questions and guidance',
  '- Login page',
  '- Sign up page',
  '- Forgot password page',
  '- Reset password page',
  '',
  'Extra facts:',
  '- PhishNet AI focuses on phishing detection and phishing awareness, not general cybersecurity only.',
  '- The system is intended to help users analyze suspicious URLs and also learn how to recognize phishing attempts.',
  '- The project is a study for BSIS 2nd year students of La Concepcion College.',
  '- The quiz feature is part of the awareness side of the system and helps users improve decision-making in phishing-related situations.',
  '- Signed-in users have access to saved progress, leaderboard participation, quiz history, badges, public profile visibility, profile notes, and rank-based profile tracking.',
  '- Guests can still try quizzes in the shared quiz interface, but their progress is limited and not fully saved.',
  '- The logo and branding are inspired by the word "fishnet," which connects to the project name PhishNet AI.',
  '- Reymond P. Joaquin is the main programmer of the system.',
  '',
  'Questions Phinny should be able to answer from project knowledge:',
  '- What is PhishNet AI?',
  '- What is the title of the study?',
  '- What does PhishNet AI do?',
  '- Who developed PhishNet AI?',
  '- What course and year level are the researchers from?',
  '- Who are the researchers of the study?',
  '- What school is involved in the project?',
  '- Who is the adviser?',
  '- What are the main features of the system?',
  '- How does the phishing scanner work?',
  '- How does the quiz system work?',
  '- What is the purpose of the leaderboard, badges, and profile?',
  '- What pages are available in the system?',
  '- Can guests use the quiz page?',
  '- What do signed-in users unlock?',
  '- Why is the system called PhishNet AI?'
].join('\n');

module.exports = {
  phishnetAssistantKnowledge
};
